# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 07:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161130_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmod',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 7, 15, 16, 364575)),
        ),
    ]
